"""
Git repository inspection.

This package provides a lightweight interface for querying git repository
state and retrieving file diffs without any GUI dependencies.
"""

from git.git_error import GitCommandError, GitError, GitNotFoundError, GitNotRepositoryError
from git.git_operations import (
    BranchInfo,
    MergeState,
    RemoteInfo,
    StashEntry,
    UpstreamStatus,
    abort_merge,
    abort_rebase,
    accept_ours,
    accept_theirs,
    add_remote,
    add_to_gitignore,
    apply_patch,
    checkout_remote_branch,
    cherry_pick,
    clean_untracked,
    commit,
    create_branch,
    create_tag,
    delete_branch,
    delete_tag,
    discard_all_changes,
    discard_changes,
    fetch,
    list_remote_branches,
    push_tags,
    rebase,
    rebase_continue,
    get_identity,
    get_merge_state,
    list_remotes,
    list_tags,
    mark_resolved,
    merge_branch,
    remove_remote,
    rename_branch,
    set_credential,
    set_identity,
    set_remote_url,
    get_branch_info,
    get_current_branch,
    get_upstream_status,
    pull,
    push,
    reset,
    revert_commit,
    stage_files,
    stash_apply,
    stash_drop,
    stash_list,
    stash_pop,
    stash_push,
    switch_branch,
    undo_last_commit,
    unstage_files,
)
from git.git_log import (
    BlameLine, CommitFileChange, CommitInfo, get_blame, get_commit_file_diff,
    get_commit_files, get_head_message, get_log, get_ref_diff_files, get_ref_file_diff
)
from git.git_repository import (
    clone_repository, find_repo_root, find_repositories, get_file_at_head, get_file_diff,
    get_staged_file_diff, get_unstaged_file_diff, init_repository, is_file_tracked, split_file_diff
)
from git.git_status import VCSFileStatus, VCSStatusCode, get_status

__all__ = [
    # Exceptions
    "GitError",
    "GitNotFoundError",
    "GitNotRepositoryError",
    "GitCommandError",

    # Repository functions
    "find_repo_root",
    "find_repositories",
    "init_repository",
    "clone_repository",
    "is_file_tracked",
    "get_file_at_head",
    "get_file_diff",
    "get_unstaged_file_diff",
    "get_staged_file_diff",
    "split_file_diff",

    # Status
    "VCSFileStatus",
    "VCSStatusCode",
    "get_status",

    # History / log
    "CommitInfo",
    "CommitFileChange",
    "BlameLine",
    "get_log",
    "get_head_message",
    "get_commit_files",
    "get_commit_file_diff",
    "get_blame",
    "get_ref_diff_files",
    "get_ref_file_diff",

    # Mutation & remote operations
    "BranchInfo",
    "MergeState",
    "StashEntry",
    "UpstreamStatus",
    "RemoteInfo",
    "get_merge_state",
    "accept_ours",
    "accept_theirs",
    "mark_resolved",
    "abort_merge",
    "abort_rebase",
    "delete_branch",
    "rename_branch",
    "merge_branch",
    "list_tags",
    "create_tag",
    "delete_tag",
    "list_remotes",
    "add_remote",
    "remove_remote",
    "set_remote_url",
    "set_credential",
    "get_identity",
    "set_identity",
    "apply_patch",
    "stage_files",
    "unstage_files",
    "discard_changes",
    "commit",
    "get_current_branch",
    "get_branch_info",
    "create_branch",
    "switch_branch",
    "fetch",
    "pull",
    "push",
    "get_upstream_status",
    "revert_commit",
    "reset",
    "undo_last_commit",
    "cherry_pick",
    "list_remote_branches",
    "checkout_remote_branch",
    "push_tags",
    "rebase",
    "rebase_continue",
    "add_to_gitignore",
    "discard_all_changes",
    "clean_untracked",
    "stash_push",
    "stash_list",
    "stash_pop",
    "stash_apply",
    "stash_drop",
]
