from enum import IntEnum, auto


class ProgrammingLanguage(IntEnum):
    """Programming language enum."""
    UNKNOWN = -1
    BASH = auto()
    C = auto()
    CPP = auto()
    CSHARP = auto()
    CSS = auto()
    GO = auto()
    DIFF = auto()
    HTML = auto()
    JAVA = auto()
    JAVASCRIPT = auto()
    JSON = auto()
    KOTLIN = auto()
    LUA = auto()
    MARKDOWN = auto()
    MENAI = auto()
    METAPHOR = auto()
    MOVE = auto()
    PHP = auto()
    PYTHON = auto()
    RUBY = auto()
    RUST = auto()
    SCHEME = auto()
    SOLIDITY = auto()
    SWIFT = auto()
    TEXT = auto()
    TOML = auto()
    TYPESCRIPT = auto()
    XML = auto()
    YAML = auto()
